# Generated by Django 6.1.1 on 2026-09-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('shop_owner', 'Retailer'), ('delivery_partner', 'Delivery partner'), ('admin', 'Admin')], db_index=True, default='customer', max_length=20),
        ),
    ]
