# Generated by Django 6.1.1 on 2026-09-15 09:48

from decimal import Decimal
import random
from datetime import timedelta
from decimal import Decimal

from django.db import migrations, models


def backfill_trips(apps, schema_editor):
    """Give existing orders a dummy distance, rider pay and trip timestamps."""
    Order = apps.get_model("delivery", "Order")
    rng = random.Random(42)
    for order in Order.objects.all():
        order.distance_km = Decimal(str(round(rng.uniform(0.8, 4.5), 1)))
        order.rider_earning = max(Decimal("25") + Decimal("7") * order.distance_km, Decimal("30")).quantize(Decimal("1"))
        if order.delivery_partner_id:
            start = order.created_at
            order.assigned_at = start + timedelta(minutes=1)
            if order.status in ("picked_up", "delivered"):
                order.reached_shop_at = start + timedelta(minutes=4)
                order.picked_up_at = start + timedelta(minutes=6)
            if order.status == "delivered":
                order.reached_customer_at = (order.delivered_at or start + timedelta(minutes=14)) - timedelta(minutes=1)
        order.save(update_fields=["distance_km", "rider_earning", "assigned_at", "reached_shop_at", "picked_up_at", "reached_customer_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_retailer_role_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='online_since',
            field=models.DateTimeField(blank=True, help_text='When the rider last went online.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Shop to customer.', max_digits=4),
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reached_customer_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reached_shop_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_earning',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Paid to the delivery partner.', max_digits=7),
        ),
        migrations.RunPython(backfill_trips, migrations.RunPython.noop),
    ]
