"""
Django settings for booze project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from decimal import Decimal
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def env(key, default=None):
    value = os.getenv(key)
    if value is None or value == "":
        return default
    return value


def env_bool(key, default=False):
    value = os.getenv(key)
    if value is None or value == "":
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(key, default=None):
    value = os.getenv(key)
    if value is None or value.strip() == "":
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]


def env_int(key, default=0):
    value = os.getenv(key)
    if value is None or value == "":
        return default
    return int(value)


def env_decimal(key, default="0"):
    value = os.getenv(key)
    if value is None or value == "":
        return Decimal(default)
    return Decimal(value)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "SECRET_KEY",
    "django-insecure-@vp6=yyg=2mxask4+3d8(_gj%qza%9u79q5=03122#zq)*-)bb",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", True)

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    ["127.0.0.1", "localhost", "boozze.pythonanywhere.com"],
)

CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    [
        "http://127.0.0.1:8000",
        "http://localhost:8000",
        "https://boozze.pythonanywhere.com",
    ],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'delivery',
    'admin',
    'rider',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'booze.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'delivery.context_processors.storefront',
                'admin.context_processors.panel',
            ],
        },
    },
]

WSGI_APPLICATION = 'booze.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = env("LANGUAGE_CODE", "en-us")

TIME_ZONE = env("TIME_ZONE", "Asia/Kolkata")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = env("STATIC_URL", "static/")
STATIC_ROOT = env("STATIC_ROOT", str(BASE_DIR / "staticfiles"))

MEDIA_URL = env("MEDIA_URL", "media/")
MEDIA_ROOT = env("MEDIA_ROOT", str(BASE_DIR / "media"))


# Auth
AUTH_USER_MODEL = 'delivery.User'
LOGIN_URL = 'delivery:login'
LOGIN_REDIRECT_URL = 'delivery:home'
LOGOUT_REDIRECT_URL = 'delivery:home'


# Booze business rules
LEGAL_DRINKING_AGE = env_int("LEGAL_DRINKING_AGE", 21)  # varies by Indian state (18 / 21 / 25) — make per-state later
ESTIMATED_DELIVERY_MINUTES = env_int("ESTIMATED_DELIVERY_MINUTES", 15)
DELIVERY_FEE = env_decimal("DELIVERY_FEE", "30")
FREE_DELIVERY_ABOVE = env_decimal("FREE_DELIVERY_ABOVE", "999")
PLATFORM_FEE = env_decimal("PLATFORM_FEE", "9")


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': env(
            "EMAIL_BACKEND",
            "django.core.mail.backends.console.EmailBackend",
        ),
    },
}
